// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: supply.proto

package supply

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplyProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height  int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XSupply []byte `protobuf:"bytes,2,opt,name=_supply,json=Supply,proto3" json:"_supply,omitempty"`
	XChange []byte `protobuf:"bytes,3,opt,name=_change,json=Change,proto3" json:"_change,omitempty"`
}

func (x *SupplyProto) Reset() {
	*x = SupplyProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyProto) ProtoMessage() {}

func (x *SupplyProto) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyProto.ProtoReflect.Descriptor instead.
func (*SupplyProto) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyProto) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SupplyProto) GetXSupply() []byte {
	if x != nil {
		return x.XSupply
	}
	return nil
}

func (x *SupplyProto) GetXChange() []byte {
	if x != nil {
		return x.XChange
	}
	return nil
}

type RewardProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Reward int64 `protobuf:"varint,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Change int64 `protobuf:"varint,3,opt,name=change,proto3" json:"change,omitempty"`
}

func (x *RewardProto) Reset() {
	*x = RewardProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardProto) ProtoMessage() {}

func (x *RewardProto) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardProto.ProtoReflect.Descriptor instead.
func (*RewardProto) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{1}
}

func (x *RewardProto) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RewardProto) GetReward() int64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *RewardProto) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

var File_supply_proto protoreflect.FileDescriptor

var file_supply_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x22, 0x57, 0x0a, 0x0b, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22,
	0x55, 0x0a, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x61, 0x74, 0x6f, 0x7a, 0x2f, 0x62, 0x65, 0x61, 0x74,
	0x6f, 0x7a, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_supply_proto_rawDescOnce sync.Once
	file_supply_proto_rawDescData = file_supply_proto_rawDesc
)

func file_supply_proto_rawDescGZIP() []byte {
	file_supply_proto_rawDescOnce.Do(func() {
		file_supply_proto_rawDescData = protoimpl.X.CompressGZIP(file_supply_proto_rawDescData)
	})
	return file_supply_proto_rawDescData
}

var file_supply_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_supply_proto_goTypes = []any{
	(*SupplyProto)(nil), // 0: supply.SupplyProto
	(*RewardProto)(nil), // 1: supply.RewardProto
}
var file_supply_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_supply_proto_init() }
func file_supply_proto_init() {
	if File_supply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_supply_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SupplyProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_supply_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RewardProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_supply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_supply_proto_goTypes,
		DependencyIndexes: file_supply_proto_depIdxs,
		MessageInfos:      file_supply_proto_msgTypes,
	}.Build()
	File_supply_proto = out.File
	file_supply_proto_rawDesc = nil
	file_supply_proto_goTypes = nil
	file_supply_proto_depIdxs = nil
}
