// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: supply.proto

package supply

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XTotalSupply  []byte                 `protobuf:"bytes,2,opt,name=_total_supply,json=TotalSupply,proto3" json:"_total_supply,omitempty"`
	AdjustHeight  int64                  `protobuf:"varint,3,opt,name=adjust_height,json=adjustHeight,proto3" json:"adjust_height,omitempty"`
	XAdjustSupply []byte                 `protobuf:"bytes,4,opt,name=_adjust_supply,json=AdjustSupply,proto3" json:"_adjust_supply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyProto) Reset() {
	*x = SupplyProto{}
	mi := &file_supply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyProto) ProtoMessage() {}

func (x *SupplyProto) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyProto.ProtoReflect.Descriptor instead.
func (*SupplyProto) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyProto) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SupplyProto) GetXTotalSupply() []byte {
	if x != nil {
		return x.XTotalSupply
	}
	return nil
}

func (x *SupplyProto) GetAdjustHeight() int64 {
	if x != nil {
		return x.AdjustHeight
	}
	return 0
}

func (x *SupplyProto) GetXAdjustSupply() []byte {
	if x != nil {
		return x.XAdjustSupply
	}
	return nil
}

type RewardProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XIssued       []byte                 `protobuf:"bytes,2,opt,name=_issued,json=Issued,proto3" json:"_issued,omitempty"`
	XWithdrawn    []byte                 `protobuf:"bytes,3,opt,name=_withdrawn,json=Withdrawn,proto3" json:"_withdrawn,omitempty"`
	XSlashed      []byte                 `protobuf:"bytes,4,opt,name=_slashed,json=Slashed,proto3" json:"_slashed,omitempty"`
	XCumulated    []byte                 `protobuf:"bytes,5,opt,name=_cumulated,json=Cumulated,proto3" json:"_cumulated,omitempty"`
	Height        int64                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardProto) Reset() {
	*x = RewardProto{}
	mi := &file_supply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardProto) ProtoMessage() {}

func (x *RewardProto) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardProto.ProtoReflect.Descriptor instead.
func (*RewardProto) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{1}
}

func (x *RewardProto) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RewardProto) GetXIssued() []byte {
	if x != nil {
		return x.XIssued
	}
	return nil
}

func (x *RewardProto) GetXWithdrawn() []byte {
	if x != nil {
		return x.XWithdrawn
	}
	return nil
}

func (x *RewardProto) GetXSlashed() []byte {
	if x != nil {
		return x.XSlashed
	}
	return nil
}

func (x *RewardProto) GetXCumulated() []byte {
	if x != nil {
		return x.XCumulated
	}
	return nil
}

func (x *RewardProto) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_supply_proto protoreflect.FileDescriptor

const file_supply_proto_rawDesc = "" +
	"\n" +
	"\fsupply.proto\x12\x06supply\"\x94\x01\n" +
	"\vSupplyProto\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\"\n" +
	"\r_total_supply\x18\x02 \x01(\fR\vTotalSupply\x12#\n" +
	"\radjust_height\x18\x03 \x01(\x03R\fadjustHeight\x12$\n" +
	"\x0e_adjust_supply\x18\x04 \x01(\fR\fAdjustSupply\"\xb1\x01\n" +
	"\vRewardProto\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x17\n" +
	"\a_issued\x18\x02 \x01(\fR\x06Issued\x12\x1d\n" +
	"\n" +
	"_withdrawn\x18\x03 \x01(\fR\tWithdrawn\x12\x19\n" +
	"\b_slashed\x18\x04 \x01(\fR\aSlashed\x12\x1d\n" +
	"\n" +
	"_cumulated\x18\x05 \x01(\fR\tCumulated\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x03R\x06heightB,Z*github.com/beatoz/beatoz-go/ctrlers/supplyb\x06proto3"

var (
	file_supply_proto_rawDescOnce sync.Once
	file_supply_proto_rawDescData []byte
)

func file_supply_proto_rawDescGZIP() []byte {
	file_supply_proto_rawDescOnce.Do(func() {
		file_supply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supply_proto_rawDesc), len(file_supply_proto_rawDesc)))
	})
	return file_supply_proto_rawDescData
}

var file_supply_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_supply_proto_goTypes = []any{
	(*SupplyProto)(nil), // 0: supply.SupplyProto
	(*RewardProto)(nil), // 1: supply.RewardProto
}
var file_supply_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_supply_proto_init() }
func file_supply_proto_init() {
	if File_supply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supply_proto_rawDesc), len(file_supply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_supply_proto_goTypes,
		DependencyIndexes: file_supply_proto_depIdxs,
		MessageInfos:      file_supply_proto_msgTypes,
	}.Build()
	File_supply_proto = out.File
	file_supply_proto_goTypes = nil
	file_supply_proto_depIdxs = nil
}
