// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: delegatee.proto

package vpower

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegateeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PubKey     []byte   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Delegators [][]byte `protobuf:"bytes,2,rep,name=delegators,proto3" json:"delegators,omitempty"`
	SumPower   int64    `protobuf:"varint,3,opt,name=sum_power,json=sumPower,proto3" json:"sum_power,omitempty"`
	SelfPower  int64    `protobuf:"varint,4,opt,name=self_power,json=selfPower,proto3" json:"self_power,omitempty"`
}

func (x *DelegateeProto) Reset() {
	*x = DelegateeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delegatee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelegateeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateeProto) ProtoMessage() {}

func (x *DelegateeProto) ProtoReflect() protoreflect.Message {
	mi := &file_delegatee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateeProto.ProtoReflect.Descriptor instead.
func (*DelegateeProto) Descriptor() ([]byte, []int) {
	return file_delegatee_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateeProto) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *DelegateeProto) GetDelegators() [][]byte {
	if x != nil {
		return x.Delegators
	}
	return nil
}

func (x *DelegateeProto) GetSumPower() int64 {
	if x != nil {
		return x.SumPower
	}
	return 0
}

func (x *DelegateeProto) GetSelfPower() int64 {
	if x != nil {
		return x.SelfPower
	}
	return 0
}

var File_delegatee_proto protoreflect.FileDescriptor

var file_delegatee_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x76, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x0f, 0x64, 0x65,
	0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x6d, 0x5f, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x75, 0x6d, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x66, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x65, 0x61, 0x74, 0x6f, 0x7a, 0x2f, 0x62, 0x65, 0x61, 0x74, 0x6f, 0x7a, 0x2d, 0x67,
	0x6f, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delegatee_proto_rawDescOnce sync.Once
	file_delegatee_proto_rawDescData = file_delegatee_proto_rawDesc
)

func file_delegatee_proto_rawDescGZIP() []byte {
	file_delegatee_proto_rawDescOnce.Do(func() {
		file_delegatee_proto_rawDescData = protoimpl.X.CompressGZIP(file_delegatee_proto_rawDescData)
	})
	return file_delegatee_proto_rawDescData
}

var file_delegatee_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_delegatee_proto_goTypes = []any{
	(*DelegateeProto)(nil), // 0: vpower.delegatee_proto
}
var file_delegatee_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_delegatee_proto_init() }
func file_delegatee_proto_init() {
	if File_delegatee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delegatee_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DelegateeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delegatee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delegatee_proto_goTypes,
		DependencyIndexes: file_delegatee_proto_depIdxs,
		MessageInfos:      file_delegatee_proto_msgTypes,
	}.Build()
	File_delegatee_proto = out.File
	file_delegatee_proto_rawDesc = nil
	file_delegatee_proto_goTypes = nil
	file_delegatee_proto_depIdxs = nil
}
