// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: delegatee.proto

package vpower

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegateeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Delegators    [][]byte               `protobuf:"bytes,2,rep,name=delegators,proto3" json:"delegators,omitempty"`
	SumPower      int64                  `protobuf:"varint,3,opt,name=sum_power,json=sumPower,proto3" json:"sum_power,omitempty"`
	SelfPower     int64                  `protobuf:"varint,4,opt,name=self_power,json=selfPower,proto3" json:"self_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateeProto) Reset() {
	*x = DelegateeProto{}
	mi := &file_delegatee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateeProto) ProtoMessage() {}

func (x *DelegateeProto) ProtoReflect() protoreflect.Message {
	mi := &file_delegatee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateeProto.ProtoReflect.Descriptor instead.
func (*DelegateeProto) Descriptor() ([]byte, []int) {
	return file_delegatee_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateeProto) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *DelegateeProto) GetDelegators() [][]byte {
	if x != nil {
		return x.Delegators
	}
	return nil
}

func (x *DelegateeProto) GetSumPower() int64 {
	if x != nil {
		return x.SumPower
	}
	return 0
}

func (x *DelegateeProto) GetSelfPower() int64 {
	if x != nil {
		return x.SelfPower
	}
	return 0
}

var File_delegatee_proto protoreflect.FileDescriptor

const file_delegatee_proto_rawDesc = "" +
	"\n" +
	"\x0fdelegatee.proto\x12\x06vpower\"\x86\x01\n" +
	"\x0fdelegatee_proto\x12\x17\n" +
	"\apub_key\x18\x01 \x01(\fR\x06pubKey\x12\x1e\n" +
	"\n" +
	"delegators\x18\x02 \x03(\fR\n" +
	"delegators\x12\x1b\n" +
	"\tsum_power\x18\x03 \x01(\x03R\bsumPower\x12\x1d\n" +
	"\n" +
	"self_power\x18\x04 \x01(\x03R\tselfPowerB,Z*github.com/beatoz/beatoz-go/ctrlers/vpowerb\x06proto3"

var (
	file_delegatee_proto_rawDescOnce sync.Once
	file_delegatee_proto_rawDescData []byte
)

func file_delegatee_proto_rawDescGZIP() []byte {
	file_delegatee_proto_rawDescOnce.Do(func() {
		file_delegatee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delegatee_proto_rawDesc), len(file_delegatee_proto_rawDesc)))
	})
	return file_delegatee_proto_rawDescData
}

var file_delegatee_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_delegatee_proto_goTypes = []any{
	(*DelegateeProto)(nil), // 0: vpower.delegatee_proto
}
var file_delegatee_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_delegatee_proto_init() }
func file_delegatee_proto_init() {
	if File_delegatee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delegatee_proto_rawDesc), len(file_delegatee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delegatee_proto_goTypes,
		DependencyIndexes: file_delegatee_proto_depIdxs,
		MessageInfos:      file_delegatee_proto_msgTypes,
	}.Build()
	File_delegatee_proto = out.File
	file_delegatee_proto_goTypes = nil
	file_delegatee_proto_depIdxs = nil
}
