// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: vpower.proto

package vpower

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerChunkProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Power         int64                  `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	TxHash        []byte                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerChunkProto) Reset() {
	*x = PowerChunkProto{}
	mi := &file_vpower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerChunkProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerChunkProto) ProtoMessage() {}

func (x *PowerChunkProto) ProtoReflect() protoreflect.Message {
	mi := &file_vpower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerChunkProto.ProtoReflect.Descriptor instead.
func (*PowerChunkProto) Descriptor() ([]byte, []int) {
	return file_vpower_proto_rawDescGZIP(), []int{0}
}

func (x *PowerChunkProto) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PowerChunkProto) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PowerChunkProto) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type VPowerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SumPower      int64                  `protobuf:"varint,1,opt,name=sum_power,json=sumPower,proto3" json:"sum_power,omitempty"`
	PowerChunks   []*PowerChunkProto     `protobuf:"bytes,2,rep,name=power_chunks,json=powerChunks,proto3" json:"power_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPowerProto) Reset() {
	*x = VPowerProto{}
	mi := &file_vpower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPowerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPowerProto) ProtoMessage() {}

func (x *VPowerProto) ProtoReflect() protoreflect.Message {
	mi := &file_vpower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPowerProto.ProtoReflect.Descriptor instead.
func (*VPowerProto) Descriptor() ([]byte, []int) {
	return file_vpower_proto_rawDescGZIP(), []int{1}
}

func (x *VPowerProto) GetSumPower() int64 {
	if x != nil {
		return x.SumPower
	}
	return 0
}

func (x *VPowerProto) GetPowerChunks() []*PowerChunkProto {
	if x != nil {
		return x.PowerChunks
	}
	return nil
}

type FrozenVPowerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundPower   int64                  `protobuf:"varint,1,opt,name=refund_power,json=refundPower,proto3" json:"refund_power,omitempty"`
	PowerChunks   []*PowerChunkProto     `protobuf:"bytes,2,rep,name=power_chunks,json=powerChunks,proto3" json:"power_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrozenVPowerProto) Reset() {
	*x = FrozenVPowerProto{}
	mi := &file_vpower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrozenVPowerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrozenVPowerProto) ProtoMessage() {}

func (x *FrozenVPowerProto) ProtoReflect() protoreflect.Message {
	mi := &file_vpower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrozenVPowerProto.ProtoReflect.Descriptor instead.
func (*FrozenVPowerProto) Descriptor() ([]byte, []int) {
	return file_vpower_proto_rawDescGZIP(), []int{2}
}

func (x *FrozenVPowerProto) GetRefundPower() int64 {
	if x != nil {
		return x.RefundPower
	}
	return 0
}

func (x *FrozenVPowerProto) GetPowerChunks() []*PowerChunkProto {
	if x != nil {
		return x.PowerChunks
	}
	return nil
}

var File_vpower_proto protoreflect.FileDescriptor

const file_vpower_proto_rawDesc = "" +
	"\n" +
	"\fvpower.proto\x12\x06vpower\"X\n" +
	"\x0fpowerChunkProto\x12\x14\n" +
	"\x05power\x18\x01 \x01(\x03R\x05power\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06height\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\fR\x06txHash\"f\n" +
	"\vVPowerProto\x12\x1b\n" +
	"\tsum_power\x18\x01 \x01(\x03R\bsumPower\x12:\n" +
	"\fpower_chunks\x18\x02 \x03(\v2\x17.vpower.powerChunkProtoR\vpowerChunks\"r\n" +
	"\x11FrozenVPowerProto\x12!\n" +
	"\frefund_power\x18\x01 \x01(\x03R\vrefundPower\x12:\n" +
	"\fpower_chunks\x18\x02 \x03(\v2\x17.vpower.powerChunkProtoR\vpowerChunksB,Z*github.com/beatoz/beatoz-go/ctrlers/vpowerb\x06proto3"

var (
	file_vpower_proto_rawDescOnce sync.Once
	file_vpower_proto_rawDescData []byte
)

func file_vpower_proto_rawDescGZIP() []byte {
	file_vpower_proto_rawDescOnce.Do(func() {
		file_vpower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpower_proto_rawDesc), len(file_vpower_proto_rawDesc)))
	})
	return file_vpower_proto_rawDescData
}

var file_vpower_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vpower_proto_goTypes = []any{
	(*PowerChunkProto)(nil),   // 0: vpower.powerChunkProto
	(*VPowerProto)(nil),       // 1: vpower.VPowerProto
	(*FrozenVPowerProto)(nil), // 2: vpower.FrozenVPowerProto
}
var file_vpower_proto_depIdxs = []int32{
	0, // 0: vpower.VPowerProto.power_chunks:type_name -> vpower.powerChunkProto
	0, // 1: vpower.FrozenVPowerProto.power_chunks:type_name -> vpower.powerChunkProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vpower_proto_init() }
func file_vpower_proto_init() {
	if File_vpower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpower_proto_rawDesc), len(file_vpower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vpower_proto_goTypes,
		DependencyIndexes: file_vpower_proto_depIdxs,
		MessageInfos:      file_vpower_proto_msgTypes,
	}.Build()
	File_vpower_proto = out.File
	file_vpower_proto_goTypes = nil
	file_vpower_proto_depIdxs = nil
}
