// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gov_params.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GovParamsProto struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Version                   int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MaxValidatorCnt           int32                  `protobuf:"varint,3,opt,name=max_validator_cnt,json=maxValidatorCnt,proto3" json:"max_validator_cnt,omitempty"`
	MinValidatorPower         int64                  `protobuf:"varint,4,opt,name=min_validator_power,json=minValidatorPower,proto3" json:"min_validator_power,omitempty"`
	MinDelegatorPower         int64                  `protobuf:"varint,5,opt,name=min_delegator_power,json=minDelegatorPower,proto3" json:"min_delegator_power,omitempty"`
	MaxValidatorsOfDelegator  int32                  `protobuf:"varint,6,opt,name=max_validators_of_delegator,json=maxValidatorsOfDelegator,proto3" json:"max_validators_of_delegator,omitempty"`
	MaxDelegatorsOfValidator  int32                  `protobuf:"varint,7,opt,name=max_delegators_of_validator,json=maxDelegatorsOfValidator,proto3" json:"max_delegators_of_validator,omitempty"`
	MinSelfPowerRate          int32                  `protobuf:"varint,8,opt,name=min_self_power_rate,json=minSelfPowerRate,proto3" json:"min_self_power_rate,omitempty"`
	MaxUpdatablePowerRate     int32                  `protobuf:"varint,9,opt,name=max_updatable_power_rate,json=maxUpdatablePowerRate,proto3" json:"max_updatable_power_rate,omitempty"`
	MaxIndividualPowerRate    int32                  `protobuf:"varint,10,opt,name=max_individual_power_rate,json=maxIndividualPowerRate,proto3" json:"max_individual_power_rate,omitempty"`
	MinBondingBlocks          int64                  `protobuf:"varint,11,opt,name=min_bonding_blocks,json=minBondingBlocks,proto3" json:"min_bonding_blocks,omitempty"`
	MinSignedBlocks           int64                  `protobuf:"varint,12,opt,name=min_signed_blocks,json=minSignedBlocks,proto3" json:"min_signed_blocks,omitempty"`
	LazyUnbondingBlocks       int64                  `protobuf:"varint,13,opt,name=lazy_unbonding_blocks,json=lazyUnbondingBlocks,proto3" json:"lazy_unbonding_blocks,omitempty"`
	XMaxTotalSupply           []byte                 `protobuf:"bytes,14,opt,name=_max_total_supply,json=MaxTotalSupply,proto3" json:"_max_total_supply,omitempty"`
	InflationWeightPermil     int32                  `protobuf:"varint,15,opt,name=inflation_weight_permil,json=inflationWeightPermil,proto3" json:"inflation_weight_permil,omitempty"`
	InflationCycleBlocks      int64                  `protobuf:"varint,16,opt,name=inflation_cycle_blocks,json=inflationCycleBlocks,proto3" json:"inflation_cycle_blocks,omitempty"`
	BondingBlocksWeightPermil int32                  `protobuf:"varint,17,opt,name=bonding_blocks_weight_permil,json=bondingBlocksWeightPermil,proto3" json:"bonding_blocks_weight_permil,omitempty"`
	RipeningBlocks            int64                  `protobuf:"varint,18,opt,name=ripening_blocks,json=ripeningBlocks,proto3" json:"ripening_blocks,omitempty"`
	XRewardPoolAddress        []byte                 `protobuf:"bytes,19,opt,name=_reward_pool_address,json=RewardPoolAddress,proto3" json:"_reward_pool_address,omitempty"`
	XDeadAddress              []byte                 `protobuf:"bytes,20,opt,name=_dead_address,json=DeadAddress,proto3" json:"_dead_address,omitempty"`
	ValidatorRewardRate       int32                  `protobuf:"varint,21,opt,name=validator_reward_rate,json=validatorRewardRate,proto3" json:"validator_reward_rate,omitempty"`
	TxFeeRewardRate           int32                  `protobuf:"varint,22,opt,name=tx_fee_reward_rate,json=txFeeRewardRate,proto3" json:"tx_fee_reward_rate,omitempty"`
	SlashRate                 int32                  `protobuf:"varint,23,opt,name=slash_rate,json=slashRate,proto3" json:"slash_rate,omitempty"`
	XGasPrice                 []byte                 `protobuf:"bytes,24,opt,name=_gas_price,json=GasPrice,proto3" json:"_gas_price,omitempty"`
	MinTrxGas                 int64                  `protobuf:"varint,25,opt,name=min_trx_gas,json=minTrxGas,proto3" json:"min_trx_gas,omitempty"`
	BlockSizeLimit            int64                  `protobuf:"varint,26,opt,name=block_size_limit,json=blockSizeLimit,proto3" json:"block_size_limit,omitempty"`
	BlockGasLimit             int64                  `protobuf:"varint,27,opt,name=block_gas_limit,json=blockGasLimit,proto3" json:"block_gas_limit,omitempty"`
	MinVotingPeriodBlocks     int64                  `protobuf:"varint,28,opt,name=min_voting_period_blocks,json=minVotingPeriodBlocks,proto3" json:"min_voting_period_blocks,omitempty"`
	MaxVotingPeriodBlocks     int64                  `protobuf:"varint,29,opt,name=max_voting_period_blocks,json=maxVotingPeriodBlocks,proto3" json:"max_voting_period_blocks,omitempty"`
	LazyApplyingBlocks        int64                  `protobuf:"varint,30,opt,name=lazy_applying_blocks,json=lazyApplyingBlocks,proto3" json:"lazy_applying_blocks,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GovParamsProto) Reset() {
	*x = GovParamsProto{}
	mi := &file_gov_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovParamsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovParamsProto) ProtoMessage() {}

func (x *GovParamsProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovParamsProto.ProtoReflect.Descriptor instead.
func (*GovParamsProto) Descriptor() ([]byte, []int) {
	return file_gov_params_proto_rawDescGZIP(), []int{0}
}

func (x *GovParamsProto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GovParamsProto) GetMaxValidatorCnt() int32 {
	if x != nil {
		return x.MaxValidatorCnt
	}
	return 0
}

func (x *GovParamsProto) GetMinValidatorPower() int64 {
	if x != nil {
		return x.MinValidatorPower
	}
	return 0
}

func (x *GovParamsProto) GetMinDelegatorPower() int64 {
	if x != nil {
		return x.MinDelegatorPower
	}
	return 0
}

func (x *GovParamsProto) GetMaxValidatorsOfDelegator() int32 {
	if x != nil {
		return x.MaxValidatorsOfDelegator
	}
	return 0
}

func (x *GovParamsProto) GetMaxDelegatorsOfValidator() int32 {
	if x != nil {
		return x.MaxDelegatorsOfValidator
	}
	return 0
}

func (x *GovParamsProto) GetMinSelfPowerRate() int32 {
	if x != nil {
		return x.MinSelfPowerRate
	}
	return 0
}

func (x *GovParamsProto) GetMaxUpdatablePowerRate() int32 {
	if x != nil {
		return x.MaxUpdatablePowerRate
	}
	return 0
}

func (x *GovParamsProto) GetMaxIndividualPowerRate() int32 {
	if x != nil {
		return x.MaxIndividualPowerRate
	}
	return 0
}

func (x *GovParamsProto) GetMinBondingBlocks() int64 {
	if x != nil {
		return x.MinBondingBlocks
	}
	return 0
}

func (x *GovParamsProto) GetMinSignedBlocks() int64 {
	if x != nil {
		return x.MinSignedBlocks
	}
	return 0
}

func (x *GovParamsProto) GetLazyUnbondingBlocks() int64 {
	if x != nil {
		return x.LazyUnbondingBlocks
	}
	return 0
}

func (x *GovParamsProto) GetXMaxTotalSupply() []byte {
	if x != nil {
		return x.XMaxTotalSupply
	}
	return nil
}

func (x *GovParamsProto) GetInflationWeightPermil() int32 {
	if x != nil {
		return x.InflationWeightPermil
	}
	return 0
}

func (x *GovParamsProto) GetInflationCycleBlocks() int64 {
	if x != nil {
		return x.InflationCycleBlocks
	}
	return 0
}

func (x *GovParamsProto) GetBondingBlocksWeightPermil() int32 {
	if x != nil {
		return x.BondingBlocksWeightPermil
	}
	return 0
}

func (x *GovParamsProto) GetRipeningBlocks() int64 {
	if x != nil {
		return x.RipeningBlocks
	}
	return 0
}

func (x *GovParamsProto) GetXRewardPoolAddress() []byte {
	if x != nil {
		return x.XRewardPoolAddress
	}
	return nil
}

func (x *GovParamsProto) GetXDeadAddress() []byte {
	if x != nil {
		return x.XDeadAddress
	}
	return nil
}

func (x *GovParamsProto) GetValidatorRewardRate() int32 {
	if x != nil {
		return x.ValidatorRewardRate
	}
	return 0
}

func (x *GovParamsProto) GetTxFeeRewardRate() int32 {
	if x != nil {
		return x.TxFeeRewardRate
	}
	return 0
}

func (x *GovParamsProto) GetSlashRate() int32 {
	if x != nil {
		return x.SlashRate
	}
	return 0
}

func (x *GovParamsProto) GetXGasPrice() []byte {
	if x != nil {
		return x.XGasPrice
	}
	return nil
}

func (x *GovParamsProto) GetMinTrxGas() int64 {
	if x != nil {
		return x.MinTrxGas
	}
	return 0
}

func (x *GovParamsProto) GetBlockSizeLimit() int64 {
	if x != nil {
		return x.BlockSizeLimit
	}
	return 0
}

func (x *GovParamsProto) GetBlockGasLimit() int64 {
	if x != nil {
		return x.BlockGasLimit
	}
	return 0
}

func (x *GovParamsProto) GetMinVotingPeriodBlocks() int64 {
	if x != nil {
		return x.MinVotingPeriodBlocks
	}
	return 0
}

func (x *GovParamsProto) GetMaxVotingPeriodBlocks() int64 {
	if x != nil {
		return x.MaxVotingPeriodBlocks
	}
	return 0
}

func (x *GovParamsProto) GetLazyApplyingBlocks() int64 {
	if x != nil {
		return x.LazyApplyingBlocks
	}
	return 0
}

var File_gov_params_proto protoreflect.FileDescriptor

const file_gov_params_proto_rawDesc = "" +
	"\n" +
	"\x10gov_params.proto\x12\x05types\"\xf7\n" +
	"\n" +
	"\x0eGovParamsProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12*\n" +
	"\x11max_validator_cnt\x18\x03 \x01(\x05R\x0fmaxValidatorCnt\x12.\n" +
	"\x13min_validator_power\x18\x04 \x01(\x03R\x11minValidatorPower\x12.\n" +
	"\x13min_delegator_power\x18\x05 \x01(\x03R\x11minDelegatorPower\x12=\n" +
	"\x1bmax_validators_of_delegator\x18\x06 \x01(\x05R\x18maxValidatorsOfDelegator\x12=\n" +
	"\x1bmax_delegators_of_validator\x18\a \x01(\x05R\x18maxDelegatorsOfValidator\x12-\n" +
	"\x13min_self_power_rate\x18\b \x01(\x05R\x10minSelfPowerRate\x127\n" +
	"\x18max_updatable_power_rate\x18\t \x01(\x05R\x15maxUpdatablePowerRate\x129\n" +
	"\x19max_individual_power_rate\x18\n" +
	" \x01(\x05R\x16maxIndividualPowerRate\x12,\n" +
	"\x12min_bonding_blocks\x18\v \x01(\x03R\x10minBondingBlocks\x12*\n" +
	"\x11min_signed_blocks\x18\f \x01(\x03R\x0fminSignedBlocks\x122\n" +
	"\x15lazy_unbonding_blocks\x18\r \x01(\x03R\x13lazyUnbondingBlocks\x12)\n" +
	"\x11_max_total_supply\x18\x0e \x01(\fR\x0eMaxTotalSupply\x126\n" +
	"\x17inflation_weight_permil\x18\x0f \x01(\x05R\x15inflationWeightPermil\x124\n" +
	"\x16inflation_cycle_blocks\x18\x10 \x01(\x03R\x14inflationCycleBlocks\x12?\n" +
	"\x1cbonding_blocks_weight_permil\x18\x11 \x01(\x05R\x19bondingBlocksWeightPermil\x12'\n" +
	"\x0fripening_blocks\x18\x12 \x01(\x03R\x0eripeningBlocks\x12/\n" +
	"\x14_reward_pool_address\x18\x13 \x01(\fR\x11RewardPoolAddress\x12\"\n" +
	"\r_dead_address\x18\x14 \x01(\fR\vDeadAddress\x122\n" +
	"\x15validator_reward_rate\x18\x15 \x01(\x05R\x13validatorRewardRate\x12+\n" +
	"\x12tx_fee_reward_rate\x18\x16 \x01(\x05R\x0ftxFeeRewardRate\x12\x1d\n" +
	"\n" +
	"slash_rate\x18\x17 \x01(\x05R\tslashRate\x12\x1c\n" +
	"\n" +
	"_gas_price\x18\x18 \x01(\fR\bGasPrice\x12\x1e\n" +
	"\vmin_trx_gas\x18\x19 \x01(\x03R\tminTrxGas\x12(\n" +
	"\x10block_size_limit\x18\x1a \x01(\x03R\x0eblockSizeLimit\x12&\n" +
	"\x0fblock_gas_limit\x18\x1b \x01(\x03R\rblockGasLimit\x127\n" +
	"\x18min_voting_period_blocks\x18\x1c \x01(\x03R\x15minVotingPeriodBlocks\x127\n" +
	"\x18max_voting_period_blocks\x18\x1d \x01(\x03R\x15maxVotingPeriodBlocks\x120\n" +
	"\x14lazy_applying_blocks\x18\x1e \x01(\x03R\x12lazyApplyingBlocksJ\x04\b\x02\x10\x03B+Z)github.com/beatoz/beatoz-go/ctrlers/typesb\x06proto3"

var (
	file_gov_params_proto_rawDescOnce sync.Once
	file_gov_params_proto_rawDescData []byte
)

func file_gov_params_proto_rawDescGZIP() []byte {
	file_gov_params_proto_rawDescOnce.Do(func() {
		file_gov_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gov_params_proto_rawDesc), len(file_gov_params_proto_rawDesc)))
	})
	return file_gov_params_proto_rawDescData
}

var file_gov_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gov_params_proto_goTypes = []any{
	(*GovParamsProto)(nil), // 0: types.GovParamsProto
}
var file_gov_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gov_params_proto_init() }
func file_gov_params_proto_init() {
	if File_gov_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gov_params_proto_rawDesc), len(file_gov_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gov_params_proto_goTypes,
		DependencyIndexes: file_gov_params_proto_depIdxs,
		MessageInfos:      file_gov_params_proto_msgTypes,
	}.Build()
	File_gov_params_proto = out.File
	file_gov_params_proto_goTypes = nil
	file_gov_params_proto_depIdxs = nil
}
