// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: trx.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrxProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Nonce         int64                  `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	From          []byte                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	XAmount       []byte                 `protobuf:"bytes,6,opt,name=_amount,json=Amount,proto3" json:"_amount,omitempty"`
	Gas           int64                  `protobuf:"varint,7,opt,name=gas,proto3" json:"gas,omitempty"`
	XGasPrice     []byte                 `protobuf:"bytes,8,opt,name=_gasPrice,json=GasPrice,proto3" json:"_gasPrice,omitempty"`
	Type          int32                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	XPayload      []byte                 `protobuf:"bytes,10,opt,name=_payload,json=Payload,proto3" json:"_payload,omitempty"`
	Sig           []byte                 `protobuf:"bytes,11,opt,name=sig,proto3" json:"sig,omitempty"`
	Payer         []byte                 `protobuf:"bytes,12,opt,name=payer,proto3" json:"payer,omitempty"`
	PayerSig      []byte                 `protobuf:"bytes,13,opt,name=payer_sig,json=payerSig,proto3" json:"payer_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxProto) Reset() {
	*x = TrxProto{}
	mi := &file_trx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxProto) ProtoMessage() {}

func (x *TrxProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxProto.ProtoReflect.Descriptor instead.
func (*TrxProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{0}
}

func (x *TrxProto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TrxProto) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TrxProto) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TrxProto) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TrxProto) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TrxProto) GetXAmount() []byte {
	if x != nil {
		return x.XAmount
	}
	return nil
}

func (x *TrxProto) GetGas() int64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *TrxProto) GetXGasPrice() []byte {
	if x != nil {
		return x.XGasPrice
	}
	return nil
}

func (x *TrxProto) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TrxProto) GetXPayload() []byte {
	if x != nil {
		return x.XPayload
	}
	return nil
}

func (x *TrxProto) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *TrxProto) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *TrxProto) GetPayerSig() []byte {
	if x != nil {
		return x.PayerSig
	}
	return nil
}

type TrxPayloadAssetTransferProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadAssetTransferProto) Reset() {
	*x = TrxPayloadAssetTransferProto{}
	mi := &file_trx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadAssetTransferProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadAssetTransferProto) ProtoMessage() {}

func (x *TrxPayloadAssetTransferProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadAssetTransferProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadAssetTransferProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{1}
}

type TrxPayloadStakingProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadStakingProto) Reset() {
	*x = TrxPayloadStakingProto{}
	mi := &file_trx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadStakingProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadStakingProto) ProtoMessage() {}

func (x *TrxPayloadStakingProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadStakingProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadStakingProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{2}
}

type TrxPayloadUnstakingProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadUnstakingProto) Reset() {
	*x = TrxPayloadUnstakingProto{}
	mi := &file_trx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadUnstakingProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadUnstakingProto) ProtoMessage() {}

func (x *TrxPayloadUnstakingProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadUnstakingProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadUnstakingProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{3}
}

func (x *TrxPayloadUnstakingProto) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type TrxPayloadWithdrawProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XReqAmt       []byte                 `protobuf:"bytes,1,opt,name=_reqAmt,json=ReqAmt,proto3" json:"_reqAmt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadWithdrawProto) Reset() {
	*x = TrxPayloadWithdrawProto{}
	mi := &file_trx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadWithdrawProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadWithdrawProto) ProtoMessage() {}

func (x *TrxPayloadWithdrawProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadWithdrawProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadWithdrawProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{4}
}

func (x *TrxPayloadWithdrawProto) GetXReqAmt() []byte {
	if x != nil {
		return x.XReqAmt
	}
	return nil
}

type TrxPayloadContractProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XData         []byte                 `protobuf:"bytes,1,opt,name=_data,json=Data,proto3" json:"_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadContractProto) Reset() {
	*x = TrxPayloadContractProto{}
	mi := &file_trx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadContractProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadContractProto) ProtoMessage() {}

func (x *TrxPayloadContractProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadContractProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadContractProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{5}
}

func (x *TrxPayloadContractProto) GetXData() []byte {
	if x != nil {
		return x.XData
	}
	return nil
}

type TrxPayloadProposalProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StartVotingHeight int64                  `protobuf:"varint,2,opt,name=start_voting_height,json=startVotingHeight,proto3" json:"start_voting_height,omitempty"`
	VotingBlocks      int64                  `protobuf:"varint,3,opt,name=voting_blocks,json=votingBlocks,proto3" json:"voting_blocks,omitempty"`
	ApplyingHeight    int64                  `protobuf:"varint,6,opt,name=applying_height,json=applyingHeight,proto3" json:"applying_height,omitempty"`
	OptType           int32                  `protobuf:"varint,4,opt,name=opt_type,json=optType,proto3" json:"opt_type,omitempty"`
	Options           [][]byte               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrxPayloadProposalProto) Reset() {
	*x = TrxPayloadProposalProto{}
	mi := &file_trx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadProposalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadProposalProto) ProtoMessage() {}

func (x *TrxPayloadProposalProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadProposalProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadProposalProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{6}
}

func (x *TrxPayloadProposalProto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrxPayloadProposalProto) GetStartVotingHeight() int64 {
	if x != nil {
		return x.StartVotingHeight
	}
	return 0
}

func (x *TrxPayloadProposalProto) GetVotingBlocks() int64 {
	if x != nil {
		return x.VotingBlocks
	}
	return 0
}

func (x *TrxPayloadProposalProto) GetApplyingHeight() int64 {
	if x != nil {
		return x.ApplyingHeight
	}
	return 0
}

func (x *TrxPayloadProposalProto) GetOptType() int32 {
	if x != nil {
		return x.OptType
	}
	return 0
}

func (x *TrxPayloadProposalProto) GetOptions() [][]byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type TrxPayloadVotingProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Choice        int32                  `protobuf:"varint,2,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadVotingProto) Reset() {
	*x = TrxPayloadVotingProto{}
	mi := &file_trx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadVotingProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadVotingProto) ProtoMessage() {}

func (x *TrxPayloadVotingProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadVotingProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadVotingProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{7}
}

func (x *TrxPayloadVotingProto) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *TrxPayloadVotingProto) GetChoice() int32 {
	if x != nil {
		return x.Choice
	}
	return 0
}

type TrxPayloadSetDocProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrxPayloadSetDocProto) Reset() {
	*x = TrxPayloadSetDocProto{}
	mi := &file_trx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrxPayloadSetDocProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxPayloadSetDocProto) ProtoMessage() {}

func (x *TrxPayloadSetDocProto) ProtoReflect() protoreflect.Message {
	mi := &file_trx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxPayloadSetDocProto.ProtoReflect.Descriptor instead.
func (*TrxPayloadSetDocProto) Descriptor() ([]byte, []int) {
	return file_trx_proto_rawDescGZIP(), []int{8}
}

func (x *TrxPayloadSetDocProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrxPayloadSetDocProto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_trx_proto protoreflect.FileDescriptor

const file_trx_proto_rawDesc = "" +
	"\n" +
	"\ttrx.proto\x12\x05types\"\xae\x02\n" +
	"\bTrxProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x03R\x05nonce\x12\x12\n" +
	"\x04from\x18\x04 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\fR\x02to\x12\x17\n" +
	"\a_amount\x18\x06 \x01(\fR\x06Amount\x12\x10\n" +
	"\x03gas\x18\a \x01(\x03R\x03gas\x12\x1b\n" +
	"\t_gasPrice\x18\b \x01(\fR\bGasPrice\x12\x12\n" +
	"\x04type\x18\t \x01(\x05R\x04type\x12\x19\n" +
	"\b_payload\x18\n" +
	" \x01(\fR\aPayload\x12\x10\n" +
	"\x03sig\x18\v \x01(\fR\x03sig\x12\x14\n" +
	"\x05payer\x18\f \x01(\fR\x05payer\x12\x1b\n" +
	"\tpayer_sig\x18\r \x01(\fR\bpayerSig\"\x1e\n" +
	"\x1cTrxPayloadAssetTransferProto\"\x18\n" +
	"\x16TrxPayloadStakingProto\"3\n" +
	"\x18TrxPayloadUnstakingProto\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\"2\n" +
	"\x17TrxPayloadWithdrawProto\x12\x17\n" +
	"\a_reqAmt\x18\x01 \x01(\fR\x06ReqAmt\".\n" +
	"\x17TrxPayloadContractProto\x12\x13\n" +
	"\x05_data\x18\x01 \x01(\fR\x04Data\"\xe6\x01\n" +
	"\x17TrxPayloadProposalProto\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x13start_voting_height\x18\x02 \x01(\x03R\x11startVotingHeight\x12#\n" +
	"\rvoting_blocks\x18\x03 \x01(\x03R\fvotingBlocks\x12'\n" +
	"\x0fapplying_height\x18\x06 \x01(\x03R\x0eapplyingHeight\x12\x19\n" +
	"\bopt_type\x18\x04 \x01(\x05R\aoptType\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\fR\aoptions\"H\n" +
	"\x15TrxPayloadVotingProto\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12\x16\n" +
	"\x06choice\x18\x02 \x01(\x05R\x06choice\"=\n" +
	"\x15TrxPayloadSetDocProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03urlB+Z)github.com/beatoz/beatoz-go/ctrlers/typesb\x06proto3"

var (
	file_trx_proto_rawDescOnce sync.Once
	file_trx_proto_rawDescData []byte
)

func file_trx_proto_rawDescGZIP() []byte {
	file_trx_proto_rawDescOnce.Do(func() {
		file_trx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trx_proto_rawDesc), len(file_trx_proto_rawDesc)))
	})
	return file_trx_proto_rawDescData
}

var file_trx_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_trx_proto_goTypes = []any{
	(*TrxProto)(nil),                     // 0: types.TrxProto
	(*TrxPayloadAssetTransferProto)(nil), // 1: types.TrxPayloadAssetTransferProto
	(*TrxPayloadStakingProto)(nil),       // 2: types.TrxPayloadStakingProto
	(*TrxPayloadUnstakingProto)(nil),     // 3: types.TrxPayloadUnstakingProto
	(*TrxPayloadWithdrawProto)(nil),      // 4: types.TrxPayloadWithdrawProto
	(*TrxPayloadContractProto)(nil),      // 5: types.TrxPayloadContractProto
	(*TrxPayloadProposalProto)(nil),      // 6: types.TrxPayloadProposalProto
	(*TrxPayloadVotingProto)(nil),        // 7: types.TrxPayloadVotingProto
	(*TrxPayloadSetDocProto)(nil),        // 8: types.TrxPayloadSetDocProto
}
var file_trx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trx_proto_init() }
func file_trx_proto_init() {
	if File_trx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trx_proto_rawDesc), len(file_trx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trx_proto_goTypes,
		DependencyIndexes: file_trx_proto_depIdxs,
		MessageInfos:      file_trx_proto_msgTypes,
	}.Build()
	File_trx_proto = out.File
	file_trx_proto_goTypes = nil
	file_trx_proto_depIdxs = nil
}
