// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gov_proposal.proto

package proposal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoterProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power         int64                  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	Choice        int32                  `protobuf:"varint,3,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoterProto) Reset() {
	*x = VoterProto{}
	mi := &file_gov_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterProto) ProtoMessage() {}

func (x *VoterProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterProto.ProtoReflect.Descriptor instead.
func (*VoterProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *VoterProto) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VoterProto) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *VoterProto) GetChoice() int32 {
	if x != nil {
		return x.Choice
	}
	return 0
}

type GovProposalHeaderProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PropType          int32                  `protobuf:"varint,1,opt,name=prop_type,json=propType,proto3" json:"prop_type,omitempty"`
	TxHash            []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	StartVotingHeight int64                  `protobuf:"varint,3,opt,name=start_voting_height,json=startVotingHeight,proto3" json:"start_voting_height,omitempty"`
	EndVotingHeight   int64                  `protobuf:"varint,4,opt,name=end_voting_height,json=endVotingHeight,proto3" json:"end_voting_height,omitempty"`
	ApplyHeight       int64                  `protobuf:"varint,5,opt,name=apply_height,json=applyHeight,proto3" json:"apply_height,omitempty"`
	TotalVotingPower  int64                  `protobuf:"varint,6,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	MajorityPower     int64                  `protobuf:"varint,7,opt,name=majority_power,json=majorityPower,proto3" json:"majority_power,omitempty"`
	Voters            []*VoterProto          `protobuf:"bytes,8,rep,name=voters,proto3" json:"voters,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GovProposalHeaderProto) Reset() {
	*x = GovProposalHeaderProto{}
	mi := &file_gov_proposal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovProposalHeaderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovProposalHeaderProto) ProtoMessage() {}

func (x *GovProposalHeaderProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovProposalHeaderProto.ProtoReflect.Descriptor instead.
func (*GovProposalHeaderProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *GovProposalHeaderProto) GetPropType() int32 {
	if x != nil {
		return x.PropType
	}
	return 0
}

func (x *GovProposalHeaderProto) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *GovProposalHeaderProto) GetStartVotingHeight() int64 {
	if x != nil {
		return x.StartVotingHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetEndVotingHeight() int64 {
	if x != nil {
		return x.EndVotingHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetApplyHeight() int64 {
	if x != nil {
		return x.ApplyHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetTotalVotingPower() int64 {
	if x != nil {
		return x.TotalVotingPower
	}
	return 0
}

func (x *GovProposalHeaderProto) GetMajorityPower() int64 {
	if x != nil {
		return x.MajorityPower
	}
	return 0
}

func (x *GovProposalHeaderProto) GetVoters() []*VoterProto {
	if x != nil {
		return x.Voters
	}
	return nil
}

type VoteOptionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        []byte                 `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Votes         int64                  `protobuf:"varint,2,opt,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOptionProto) Reset() {
	*x = VoteOptionProto{}
	mi := &file_gov_proposal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOptionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOptionProto) ProtoMessage() {}

func (x *VoteOptionProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOptionProto.ProtoReflect.Descriptor instead.
func (*VoteOptionProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *VoteOptionProto) GetOption() []byte {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *VoteOptionProto) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

type GovProposalProto struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Header        *GovProposalHeaderProto `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Options       []*VoteOptionProto      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	MajorOption   *VoteOptionProto        `protobuf:"bytes,3,opt,name=major_option,json=majorOption,proto3" json:"major_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovProposalProto) Reset() {
	*x = GovProposalProto{}
	mi := &file_gov_proposal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovProposalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovProposalProto) ProtoMessage() {}

func (x *GovProposalProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovProposalProto.ProtoReflect.Descriptor instead.
func (*GovProposalProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *GovProposalProto) GetHeader() *GovProposalHeaderProto {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GovProposalProto) GetOptions() []*VoteOptionProto {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GovProposalProto) GetMajorOption() *VoteOptionProto {
	if x != nil {
		return x.MajorOption
	}
	return nil
}

var File_gov_proposal_proto protoreflect.FileDescriptor

const file_gov_proposal_proto_rawDesc = "" +
	"\n" +
	"\x12gov_proposal.proto\x12\x05types\"T\n" +
	"\n" +
	"VoterProto\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x14\n" +
	"\x05power\x18\x02 \x01(\x03R\x05power\x12\x16\n" +
	"\x06choice\x18\x03 \x01(\x05R\x06choice\"\xcd\x02\n" +
	"\x16GovProposalHeaderProto\x12\x1b\n" +
	"\tprop_type\x18\x01 \x01(\x05R\bpropType\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12.\n" +
	"\x13start_voting_height\x18\x03 \x01(\x03R\x11startVotingHeight\x12*\n" +
	"\x11end_voting_height\x18\x04 \x01(\x03R\x0fendVotingHeight\x12!\n" +
	"\fapply_height\x18\x05 \x01(\x03R\vapplyHeight\x12,\n" +
	"\x12total_voting_power\x18\x06 \x01(\x03R\x10totalVotingPower\x12%\n" +
	"\x0emajority_power\x18\a \x01(\x03R\rmajorityPower\x12)\n" +
	"\x06voters\x18\b \x03(\v2\x11.types.VoterProtoR\x06voters\"?\n" +
	"\x0fvoteOptionProto\x12\x16\n" +
	"\x06option\x18\x01 \x01(\fR\x06option\x12\x14\n" +
	"\x05votes\x18\x02 \x01(\x03R\x05votes\"\xb6\x01\n" +
	"\x10GovProposalProto\x125\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.types.GovProposalHeaderProtoR\x06header\x120\n" +
	"\aoptions\x18\x02 \x03(\v2\x16.types.voteOptionProtoR\aoptions\x129\n" +
	"\fmajor_option\x18\x03 \x01(\v2\x16.types.voteOptionProtoR\vmajorOptionB2Z0github.com/beatoz/beatoz-go/ctrlers/gov/proposalb\x06proto3"

var (
	file_gov_proposal_proto_rawDescOnce sync.Once
	file_gov_proposal_proto_rawDescData []byte
)

func file_gov_proposal_proto_rawDescGZIP() []byte {
	file_gov_proposal_proto_rawDescOnce.Do(func() {
		file_gov_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gov_proposal_proto_rawDesc), len(file_gov_proposal_proto_rawDesc)))
	})
	return file_gov_proposal_proto_rawDescData
}

var file_gov_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gov_proposal_proto_goTypes = []any{
	(*VoterProto)(nil),             // 0: types.VoterProto
	(*GovProposalHeaderProto)(nil), // 1: types.GovProposalHeaderProto
	(*VoteOptionProto)(nil),        // 2: types.voteOptionProto
	(*GovProposalProto)(nil),       // 3: types.GovProposalProto
}
var file_gov_proposal_proto_depIdxs = []int32{
	0, // 0: types.GovProposalHeaderProto.voters:type_name -> types.VoterProto
	1, // 1: types.GovProposalProto.header:type_name -> types.GovProposalHeaderProto
	2, // 2: types.GovProposalProto.options:type_name -> types.voteOptionProto
	2, // 3: types.GovProposalProto.major_option:type_name -> types.voteOptionProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gov_proposal_proto_init() }
func file_gov_proposal_proto_init() {
	if File_gov_proposal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gov_proposal_proto_rawDesc), len(file_gov_proposal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gov_proposal_proto_goTypes,
		DependencyIndexes: file_gov_proposal_proto_depIdxs,
		MessageInfos:      file_gov_proposal_proto_msgTypes,
	}.Build()
	File_gov_proposal_proto = out.File
	file_gov_proposal_proto_goTypes = nil
	file_gov_proposal_proto_depIdxs = nil
}
