// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: gov_proposal.proto

package proposal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power   int64  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	Choice  int32  `protobuf:"varint,3,opt,name=choice,proto3" json:"choice,omitempty"`
}

func (x *VoterProto) Reset() {
	*x = VoterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gov_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterProto) ProtoMessage() {}

func (x *VoterProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterProto.ProtoReflect.Descriptor instead.
func (*VoterProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *VoterProto) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VoterProto) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *VoterProto) GetChoice() int32 {
	if x != nil {
		return x.Choice
	}
	return 0
}

type GovProposalHeaderProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropType          int32         `protobuf:"varint,1,opt,name=prop_type,json=propType,proto3" json:"prop_type,omitempty"`
	TxHash            []byte        `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	StartVotingHeight int64         `protobuf:"varint,3,opt,name=start_voting_height,json=startVotingHeight,proto3" json:"start_voting_height,omitempty"`
	EndVotingHeight   int64         `protobuf:"varint,4,opt,name=end_voting_height,json=endVotingHeight,proto3" json:"end_voting_height,omitempty"`
	ApplyHeight       int64         `protobuf:"varint,5,opt,name=apply_height,json=applyHeight,proto3" json:"apply_height,omitempty"`
	TotalVotingPower  int64         `protobuf:"varint,6,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	MajorityPower     int64         `protobuf:"varint,7,opt,name=majority_power,json=majorityPower,proto3" json:"majority_power,omitempty"`
	Voters            []*VoterProto `protobuf:"bytes,8,rep,name=voters,proto3" json:"voters,omitempty"`
}

func (x *GovProposalHeaderProto) Reset() {
	*x = GovProposalHeaderProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gov_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GovProposalHeaderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovProposalHeaderProto) ProtoMessage() {}

func (x *GovProposalHeaderProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovProposalHeaderProto.ProtoReflect.Descriptor instead.
func (*GovProposalHeaderProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *GovProposalHeaderProto) GetPropType() int32 {
	if x != nil {
		return x.PropType
	}
	return 0
}

func (x *GovProposalHeaderProto) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *GovProposalHeaderProto) GetStartVotingHeight() int64 {
	if x != nil {
		return x.StartVotingHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetEndVotingHeight() int64 {
	if x != nil {
		return x.EndVotingHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetApplyHeight() int64 {
	if x != nil {
		return x.ApplyHeight
	}
	return 0
}

func (x *GovProposalHeaderProto) GetTotalVotingPower() int64 {
	if x != nil {
		return x.TotalVotingPower
	}
	return 0
}

func (x *GovProposalHeaderProto) GetMajorityPower() int64 {
	if x != nil {
		return x.MajorityPower
	}
	return 0
}

func (x *GovProposalHeaderProto) GetVoters() []*VoterProto {
	if x != nil {
		return x.Voters
	}
	return nil
}

type VoteOptionProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option []byte `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Votes  int64  `protobuf:"varint,2,opt,name=votes,proto3" json:"votes,omitempty"`
}

func (x *VoteOptionProto) Reset() {
	*x = VoteOptionProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gov_proposal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteOptionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOptionProto) ProtoMessage() {}

func (x *VoteOptionProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOptionProto.ProtoReflect.Descriptor instead.
func (*VoteOptionProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *VoteOptionProto) GetOption() []byte {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *VoteOptionProto) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

type GovProposalProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *GovProposalHeaderProto `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Options     []*VoteOptionProto      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	MajorOption *VoteOptionProto        `protobuf:"bytes,3,opt,name=major_option,json=majorOption,proto3" json:"major_option,omitempty"`
}

func (x *GovProposalProto) Reset() {
	*x = GovProposalProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gov_proposal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GovProposalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovProposalProto) ProtoMessage() {}

func (x *GovProposalProto) ProtoReflect() protoreflect.Message {
	mi := &file_gov_proposal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovProposalProto.ProtoReflect.Descriptor instead.
func (*GovProposalProto) Descriptor() ([]byte, []int) {
	return file_gov_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *GovProposalProto) GetHeader() *GovProposalHeaderProto {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GovProposalProto) GetOptions() []*VoteOptionProto {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GovProposalProto) GetMajorOption() *VoteOptionProto {
	if x != nil {
		return x.MajorOption
	}
	return nil
}

var File_gov_proposal_proto protoreflect.FileDescriptor

var file_gov_proposal_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x6f, 0x76, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x0a, 0x56,
	0x6f, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x22, 0xcd, 0x02, 0x0a, 0x16, 0x47, 0x6f, 0x76, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x76, 0x6f, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x73, 0x74, 0x61, 0x72, 0x74, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x65,
	0x6e, 0x64, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x76, 0x6f, 0x74, 0x69, 0x6e,
	0x67, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x06, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x56,
	0x6f, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x76, 0x6f, 0x74, 0x65, 0x72,
	0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x76, 0x6f, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x6f, 0x74,
	0x65, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x10, 0x47, 0x6f, 0x76, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x35, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x47, 0x6f, 0x76, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x30,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x39, 0x0a, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x6f, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b,
	0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x61, 0x74, 0x6f, 0x7a,
	0x2f, 0x62, 0x65, 0x61, 0x74, 0x6f, 0x7a, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x65,
	0x72, 0x73, 0x2f, 0x67, 0x6f, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gov_proposal_proto_rawDescOnce sync.Once
	file_gov_proposal_proto_rawDescData = file_gov_proposal_proto_rawDesc
)

func file_gov_proposal_proto_rawDescGZIP() []byte {
	file_gov_proposal_proto_rawDescOnce.Do(func() {
		file_gov_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_gov_proposal_proto_rawDescData)
	})
	return file_gov_proposal_proto_rawDescData
}

var file_gov_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gov_proposal_proto_goTypes = []any{
	(*VoterProto)(nil),             // 0: types.VoterProto
	(*GovProposalHeaderProto)(nil), // 1: types.GovProposalHeaderProto
	(*VoteOptionProto)(nil),        // 2: types.voteOptionProto
	(*GovProposalProto)(nil),       // 3: types.GovProposalProto
}
var file_gov_proposal_proto_depIdxs = []int32{
	0, // 0: types.GovProposalHeaderProto.voters:type_name -> types.VoterProto
	1, // 1: types.GovProposalProto.header:type_name -> types.GovProposalHeaderProto
	2, // 2: types.GovProposalProto.options:type_name -> types.voteOptionProto
	2, // 3: types.GovProposalProto.major_option:type_name -> types.voteOptionProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gov_proposal_proto_init() }
func file_gov_proposal_proto_init() {
	if File_gov_proposal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gov_proposal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VoterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gov_proposal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GovProposalHeaderProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gov_proposal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VoteOptionProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gov_proposal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GovProposalProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gov_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gov_proposal_proto_goTypes,
		DependencyIndexes: file_gov_proposal_proto_depIdxs,
		MessageInfos:      file_gov_proposal_proto_msgTypes,
	}.Build()
	File_gov_proposal_proto = out.File
	file_gov_proposal_proto_rawDesc = nil
	file_gov_proposal_proto_goTypes = nil
	file_gov_proposal_proto_depIdxs = nil
}
